/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-MidwesternInteractive-y7CrGNEDDmmbnthg9v0BZt9FAjOAb-Wz",
  "version": "2020-11-20"
}

export default ebconfig;